### ISSUE TITLE
proto cannot install deno in windows.

### ISSUE THREAD

**Issue by lazex** [moonrepo/deno-plugin#18]
Powershell log is here.

```
PowerShell 7.4.1
PS C:\Users\WDAGUtilityAccount> proto install node
⠁ Installing Node.js 21.7.0
[ INFO 2024-03-07 23:25:38.374] proto::commands::install:install  Node.js has been installed to ~\.proto\tools\node\21.7.0!
PS C:\Users\WDAGUtilityAccount> proto install deno
⠁ Installing Deno 1.41.1
⠁ Installing Deno 1.41.1
Error: [31mplugin::http[0m

  [31m×[0m Failed to make HTTP request for [38;5;39mhttps://dl.deno.land/release/v1.41.1/deno-x86_64-pc-windows-msvc.zip[0m.
[31m  ├─▶ [0merror sending request for url (https://dl.deno.land/release/v1.41.1/deno-x86_64-pc-windows-msvc.zip): error
[31m  │   [0mtrying to connect: invalid peer certificate: UnknownIssuer
[31m  ├─▶ [0merror trying to connect: invalid peer certificate: UnknownIssuer
[31m  ╰─▶ [0minvalid peer certificate: UnknownIssuer
```

```
proto 0.31.3
```

I was able to install Node.js.
But deno failed.

I can access the URL (https://dl.deno.land/release/v1.41.1/deno-x86_64-pc-windows-msvc.zip) and download the zip file using Edge from the Windows device.

**Comment by milesj** [comment]
@lazex Are you behind a firewall or intranet or something like that that would block the ssl handshake?

You can try these settings to work around it: https://moonrepo.dev/docs/proto/config#settingshttp

**Comment by lazex** [comment]
> Are you behind a firewall or intranet or something like that that would block the ssl handshake?

No.
But, I use proto inside Windows Sandbox.
Is this relevant?

> You can try these settings to work around it: https://moonrepo.dev/docs/proto/config#settingshttp

Thanks.
This works.

```
[settings.http]
allow-invalid-certs = true
```
